config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"

  get 'my_friends', to: "users#my_friends"

  delete 'remove_friend/:id', to: "users#remove_friend", as: "remove_friend"

  get 'search_stock', to: "stocks#search"
  get 'search_friend', to: "users#search"

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  def self.check_friend?(current_user_id, friend_id)
    where(user_id: current_user_id,  friend_id: friend_id).first
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks 
  has_many :users, through: :user_stocks

  def self.check_db?(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
    #   secret_token: "sk_09d31793698545e3bcb1ac8374037cb7",
      endpoint: "https://cloud.iexapis.com/v1",
    )

    # client.price(ticker_symbol)
    begin
        new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol).to_i)
    rescue => exceptions
        return nil
    end        
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_track?(ticker_symbol)
    stock = Stock.check_db?(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_track?(ticker_symbol)
  end

  def is_friend?(friend, user)
    # binding.pry
    already_friend = Friendship.check_friend?(user.id, friend.id)
    return false unless already_friend 
    # binding.pry
    friends.where(id: friend.id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        # render "users/my_portfolio"
        if current_user.can_track_stock?(@stock.ticker)
          @stock.save
          UserStock.create(user_id: current_user.id, stock_id: @stock.id)
          flash[:alert] = "Successfully added, Stock to your Portfolio!"
          redirect_to my_portfolio_path
        elsif current_user.stock_already_track?(@stock.ticker)
          flash[:alert] = "User already tracking this stock!"
          redirect_to my_portfolio_path
        else
          flash[:alert] = "You are already tracking 10 stocks!"
          redirect_to my_portfolio_path
        end
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:alert] = "#{stock.ticker} removed from your portfolio."
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end


  def show
    @user = User.find(params[:id])
  end

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    # binding.pry
    # @tracked_stocks = current_user.stocks
    @my_friends = current_user.friends
  end


  def remove_friend
    friend = User.find(params[:id])
    remove_friend = Friendship.where(user_id: current_user.id, friend_id: friend.id).first
    remove_friend.destroy
    flash[:alert] = "#{friend.first_name} removed from your following list."
    redirect_to my_friends_path
  end

  def search
    if params[:friend].present?
      @friend = User.where(first_name: params[:friend]).first
      if @friend
        # render "users/my_portfolio"
        if @friend.email == current_user.email
          flash[:alert] = "User Not Found!"
          redirect_to my_friends_path
        elsif !current_user.is_friend?(@friend, current_user)
          Friendship.create(user_id: current_user.id, friend_id: @friend.id)
          flash[:alert] = "#{@friend.first_name}, Successfully added to your following list."
          redirect_to my_friends_path
        else
          flash[:alert] = "#{@friend.first_name} is already in your following list."
          redirect_to my_friends_path
        end
      else
        flash[:alert] = "User Not Found!"
        redirect_to my_friends_path
      end
    else
      flash[:alert] = "Please enter a name to search"
      redirect_to my_friends_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Fist Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <%@my_friends.each do |friend|%>
        <tr>
          <th scope="row"><%= friend.email%></th>
          <td><%= friend.first_name%></td>
          <td><%= friend.last_name%></td>
          <td class="space-between">
          <%= link_to "View Profile", user_path(friend), class: "btn btn-xs btn-info" %>
          <%= button_to "Stop Following", remove_friend_path(friend), method: :delete, class: "btn btn-xs btn-warning" %>
          </td>
        </tr>
       <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to "Finance Tracker", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item disabled">
            <%= link_to "My Portfolio", my_portfolio_path, class:"nav-link"%>
          </li>
          <li class="nav-item disabled">
            <%= link_to "My Friends", my_friends_path, class:"nav-link"%>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Edit Profile</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
         
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= button_to "Sign out", destroy_user_session_path, class:"btn btn-xs", method: :delete %>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <footer>
      <p>
        Created with <i class="fa fa-heart"></i> by
        <a target="_blank" href="https://florin-pop.com">Vishal Prakash Maurya</a>
        - Read how I created this
        <a target="_blank" href="https://florin-pop.com/blog/2019/04/profile-card-design">here</a>
        - Design made by
        <a target="_blank" href="https://dribbble.com/shots/6276930-Profile-Card-UI-Design">Vishal</a>
      </p>
    </footer>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <%@tracked_stocks.each do |stock|%>
        <tr>
          <th scope="row"><%= stock.ticker%></th>
          <td><%= stock.name%></td>
          <td><%= stock.last_price%></td>
          <td><%= button_to "Remove", user_stock_path(stock),method: :delete, class: "btn btn-xs btn-warning" %></td>
        </tr>
       <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="card card-header col-3">
    <div class="result-block">
      <strong>Symbol: </strong><%= @stock.ticker%>
    </div>
    <div class="result-block">
      <strong>Name: </strong><%= @stock.name%>
    </div>
    <div class="result-block">
      <strong>Last price: </strong><%= @stock.last_price%>
    </div>
  </div>
<% end %>
<div id="results"></div>

app/views/users/_result.js.erb
alert("hello world");

app/views/users/index.html.erb
<h1>
Hello user index
</h1>

app/views/users/my_friends.html.erb
<h1>
  Friends
</h1>
<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, method: :get, remote: true do %>
    <div class="form-group row">
      <div class="col-sm-9 no-padding-right">
        <%= text_field_tag :friend, params[:friend], placeholder: "Type name", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-padding-left">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if !@my_friends.empty?%>
  <%= render partial: "friends/list"%>
<%end%>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search Stock</h3>
  <%= form_tag search_stock_path, method: :get, remote: true do %>
    <div class="form-group row">
      <div class="col-sm-9 no-padding-right">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-padding-left">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= render partial: "users/result" %>
<div id="results">
</div>
<% if !@tracked_stocks.empty?%>
  <%= render partial: "stocks/list"%>
<%end%>

app/views/users/show.html.erb
<div class="card-container">
  <span class="pro">PRO</span>
  <img class="round" src="https://randomuser.me/api/portraits/men/79.jpg" alt="user" />
  <h3><%= @user.first_name %></h3>
  <h6>New York</h6>
  <p><%= @user.email %></p>
  <div class="buttons">
    <%= button_to "Portfolio", my_portfolio_path, method: :get, class:"btn-primary"%>   
    <button class="primary ghost">
      Following
    </button>
  </div>
  <div class="skills">
    <h6>Following</h6>
    <ul>
      <% @user.friends.each do |friend|%>
        <li><%= friend.first_name%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>
  Hello from the welcome page....
</h1>
<%= button_to 'Sign out', destroy_user_session_path, method: :delete%>